name: Generate API Documentation

on:
  push:
    branches:
      - main
      - auto-docs

jobs:
  build-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.x"

    - name: Setup DocFx
      uses: clFaster/docfx-setup-action@v1

    - name: Build Documentation
      uses: clFaster/docfx-build-action@v1
      with:
        docfx-file-path: "docfx.json"
        docfx-output-path: "Docs"

    - name: Upload Docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: Docs
        path: Docs

  sync-wiki:
    runs-on: ubuntu-latest
    needs: build-docs

    steps:

    - name: Download Docs artifact
      uses: actions/download-artifact@v3
      with:
        name: Docs
        path: Docs

    - name: DocFxToMarkdown
      uses: fillefilip8/DocFxToMarkdown@1.4.0
      with:
        input-folder: Docs
        output-folder: wiki
    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: https://github.com/MRfantastic3DGamer/nodify/wiki
        path: wiki

    - name: Copy generated docs to wiki
      run: cp -r Docs/* wiki/

    - name: Sync Wiki
      uses: joeizzard/action-wiki-sync@master
      with:
        username: MRfantastic3DGamer
        access_token: ${{ secrets.GITHUB_TOKEN }}
        wiki_folder: "wiki"
        commit_username: 'MRfantastic3DGamer'
        commit_email: 'dhruvtgs003@gmail.com'
        commit_message: 'action: wiki sync'
