name: Generate API Documentation

on:
  push:
    branches:
      - main
      - auto-docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: DocFX Publish
  # You may pin to the exact commit or the version.
  # uses: frankhaugen/frank-docfx-publish@ae488e9172294f60ab21755503bd8f07ee5fce0c
    - name: DocFX Publish
      uses: frankhaugen/frank-docfx-publish@1.0
